### ISSUE TITLE
placeholder text persists when field is input

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/vkirirom.com#19]
See image. Placeholder text should be removed once the user starts typing. Ideally, we should use material design principles for the form label/placeholder text... having the placeholder text initially in the form field, and then move to the top line once user starts to input:

https://material.io/design/components/text-fields.html

![image](https://user-images.githubusercontent.com/5694308/58446482-15278880-812b-11e9-8e89-b8199eb145e4.png)

**Comment by atharva3010** [comment]
That is probably due to the auto form fill, it's an issue with the type of event the autofill emits.  
It is supposed to disappear as soon as it is input, but it can vary from device to device.  
For eg: In my device, it works perfectly fine  
  
![wddww](https://user-images.githubusercontent.com/34229217/58448802-9deff580-8126-11e9-86f1-17a13491e1c8.PNG)
